### ISSUE TITLE
[Android Bootcamp] Project 2: Article Search - Ready for Review

### ISSUE THREAD

**Issue by sammsiontir** [sammsiontir/NYTimes#2]
My app is complete, please review. /cc @codepathreview @codepath

**Comment by codepathreview** [comment]
:+1: Excellent work. A few notes after checking out the code:
- Properly reused the single base method in search activity to fetch results for both initial load and the pagination
- Nice to see you added the search box to the ActionBar!
- Properly used spinners (with populated values) to allow users to select filters
- One thing to consider is rather than sending and returning all the filter values separately as keys, might have introduced a parcelable model (i.e `Filters`) representing all the filters which were passed back and forth between activities within the bundle.
-  Nice job adding the share intent to the article detail view!
- Consider adding [progress bars](http://guides.codepath.com/android/Handling-ProgressBars#progress-within-actionbar) to your app whenever a network request goes out

Also, here's a more detailed [Project 2 Feedback Guide here](http://courses.codepath.com/snippets/intro_to_android/project_2_feedback) which covers the most common issues with this submitted project. Read through the [feedback guide point-by-point](http://courses.codepath.com/snippets/intro_to_android/project_2_feedback) to determine how you could improve your submission.

Let us know if you have any other thoughts or questions about this assignment. The next assignment (Twitter Client) will be especially important since it introduces the majority of the remaining pieces necessary to build a fully functional API client with complex feeds of data and user creation.
